### ISSUE TITLE
Will lvgl-v8 be supported?

### ISSUE THREAD

**Issue by lanistor** [martinberlin/lvgl_epaper_drivers#2]
Thanks for developed such an amazing library, we really need it.

Will lvgl-v8 be supported?
The flex layout is really useful.

**Comment by martinberlin** [comment]
Hello,
I still didn’t tried it but I hope won’t be much of a hassle to port it.
Anyways there a [pull request](https://github.com/lvgl/lvgl_esp32_drivers/pull/75) made in the original repository and I’m not sure if this proposal will be ever accepted to be part of official LVGL.

**Comment by martinberlin** [comment]
Are you still interested in trying this with epaper? Days ago I made some tests with a 9.7” display and epdiy V7 
https://x.com/martinfasani/status/1694079978315411560

**Comment by martinberlin** [comment]
@lanistor can you try to clone this repository using branch **lvgl-83**
https://github.com/martinberlin/lv_port_esp32-epaper/tree/12/lvgl-83  (And updating all submodules to latest stand)

     git submodule update --recursive --remote

Only thing pending is to correct examples since they need some minor alterations so they compile in ESP-IDF 5.1

**Comment by lanistor** [comment]
I had changed to compatible with `v8`, using `esp-idf 4.4`: https://github.com/flickerlist/lvgl_epaper_drivers/tree/release/monochrome
